### ISSUE TITLE
xscreensavers don't work with new cinnamon-screensaver when on battery

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-screensaver#176]
Version 3.2.9: Choose any xscreensaver -> screen is dimmed with wallpaper shown as if the cinnnemon-screensaver is active, but without clock or something (empty screen).
Xscreensavers reinstalled - no change.

**Comment by mtwebster** [comment]
Do you have cinnamon-screensaver-x-plugin installed?

**Comment by Mintulix** [comment]
It worked before so I thought I don't have to install something. I checked to be sure - it's installed (v. 3.2.9+serena).
BUT - I reinstalled this, too. Now it works! Either it has to be reinitialized after the update or the reason is something else I don't know.
Feel free to close this issue, but please keep it in mind if someone else has this problem, too. Thanks.

**Comment by Mintulix** [comment]
It's back again, so reinstalling cinnamon-screensaver-x-plugin has and had no effect.

**Comment by Mintulix** [comment]
Got it! Pulled the plug, and instantly any xscreensaver reverted to the dimmed wallpaper as described in my first post. Put power back in, xscreensaver continues. Great!

What do you need to reproduce this?
inxi -g
Graphics:  Card-1: Intel 3rd Gen Core processor Graphics Controller
           Card-2: Advanced Micro Devices [AMD/ATI] Venus XT [Radeon HD 8870M / R9 M270X/M370X]
           Display Server: X.Org 1.18.4 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.21hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile
           GLX Version: 3.0 Mesa 11.2.0

cat /sys/kernel/debug/vgaswitcheroo/switch
0:IGD:+:Pwr:0000:00:02.0
1:DIS: :DynOff:0000:01:00.0

**Comment by mtwebster** [comment]
Wait - pulled the plug?  Your power plug?

This is intentional (though clearly not explained well enough) - sorry - on battery power xscreensavers are prevented from running because they're ridiculously resource-intensive.

**Comment by Mintulix** [comment]
Sorry, I meant the power plug, yes. If this is the intended behavior, you can close this issue. But then it's definitely a new behavior since LM 18.1. And when there is this fallback, then why not use the default cinnamon-sreensaver instead of showing just the wallpaper?

**Comment by mtwebster** [comment]
Wallpaper is the default screensaver - you may have the clock turned off (check the screensaver settings).

**Comment by Mintulix** [comment]
The clock is turned on (no customizations), and it's working as intended when I select cinnamon-screensaver. When I use xscreensaver with battery, there's no clock (waited more than 30 seconds to be sure).
You can't reproduce this? However this is really minor (the behavior should be explained somewhere, though).

**Comment by Mintulix** [comment]
Happy new year! Clock instead of xscreensaver is fixed now (clock is shown).
However - this leads to a new glitch: when you put the power plug in while the dimmed background with clock is shown, it switches to xscreensaver (ok), but the clock is still shown (and that doesn't change after 30 seconds).

**Comment by mtwebster** [comment]
Should be fixed by this: https://github.com/linuxmint/cinnamon-screensaver/commit/6dcb4b380799d08fdb5ad013123021b56679baf2

**Comment by Mintulix** [comment]
Latest issue is still there. I repeat:
When you put the power plug in while the dimmed background with clock is shown, it switches to xscreensaver (ok), but the clock is still shown (and that doesn't change after 30 seconds).
I'm sure this is reproducible. However,  this is minor, so fix it or leave it.

**Comment by mtwebster** [comment]
This isn't in a release yet - did you apply that patch manually?

**Comment by Mintulix** [comment]
Ah, no, I didn't. Will wait for the official new version. Thank you.
