### ISSUE TITLE
Upon wake, the desktop was visible briefly before the lock screen showed

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-screensaver#440]
### Distribution

Mint 21.2

### Package version

5.8.1

### Graphics hardware in use

Intel onchip; Mesa

### Frequency

Only occasionally

### Bug description

The desktop - including icons, conky, dock (Plank) - was visible for approximately a third of a second upon wake and before the lock screen. This is a security problem as well as behaviour that throws the user.

### Steps to reproduce

Unknown. I have not seen the problem before - except when I had an external monitor attached (which I did not have this time): see #406.

What trigged the problem this time was simply waking the laptop (by pressing a key on its keyboard). The machine has been asleep for some eighteen hours.

### Expected behavior

The desktop should not be visible until one has unlocked the PC.

### Additional information

```
$ cinnamon-screensaver --debug --hold
Fractional scaling active: False
Trying to connect to logind...
Starting screensaver...
Debug mode active
Cinnamon Screensaver support not found in current theme - adding some...
service: 'GetActive' received, poking application.
service: 'GetActive' received, poking application.
org.gnome.ScreenSaver is gone from the session bus
org.mate.ScreenSaver is gone from the session bus
service: 'GetActive' received, poking application.
login client: found session path for user '<me>' (session_id: c2): /org/freedesktop/login1/session/c2
Successfully using logind
```

An excerpt from .xsession-errors:

```
cinnamon-session[4122]: WARNING: t+731.43769s: Detected that screensaver has appeared on the bus
log_ksystemlog: Log manager is not yet initialized
cinnamon-session[4122]: WARNING: t+872.62203s: Detected that screensaver has left the bus
cinnamon-session[4122]: WARNING: t+878.17943s: Detected that screensaver has left the bus
** (csd-automount:4293): WARNING **: 01:47:04.868: Can't call GetActive() on the ScreenSaver object: Cannot invoke method; proxy is for the well-known name “org.cinnamon.ScreenSaver” without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
mint-common (WARN): Process remote: Server returned status 404: Not Found
cinnamon-session[4122]: WARNING: t+991.45039s: Detected that screensaver has appeared on the bus
```

```
$ cat /var/log/syslog grep ScreenSaver
[. . .]
Aug 20 01:42:15 x1 systemd[1]: systemd-suspend.service: Deactivated successfully.
Aug 20 01:42:15 x1 systemd[1]: Finished System Suspend.
Aug 20 01:42:15 x1 systemd[1]: Stopped target Sleep.
Aug 20 01:42:15 x1 systemd[1]: Reached target Suspend.
Aug 20 01:42:15 x1 systemd[1]: Stopped target Suspend.
Aug 20 01:42:15 x1 systemd-networkd[967]: lo: Reset carrier
[. . .]
Aug 20 01:42:16 x1 systemd-networkd[967]: enp0s31f6: Link UP
Aug 20 01:42:16 x1 systemd-networkd[967]: wlp2s0: Link UP
[. . .]
Aug 20 01:42:22 x1 cinnamon-screensaver-pam-helper: pam_ecryptfs: seteuid error
Aug 20 01:42:30 x1 systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
Aug 20 01:42:45 x1 systemd[1]: systemd-localed.service: Deactivated successfully.
Aug 20 01:42:52 x1 cinnamon-session[4122]: WARNING: t+625.67715s: Detected that screensaver has left the bus
Aug 20 01:42:52 x1 org.cinnamon.ScreenSaver[20202]: Error in sys.excepthook:
Aug 20 01:42:52 x1 org.cinnamon.ScreenSaver[20202]: Original exception was:
Aug 20 01:42:52 x1 org.cinnamon.ScreenSaver[20202]: Error in sys.excepthook:
Aug 20 01:42:52 x1 org.cinnamon.ScreenSaver[20202]: Original exception was:
Aug 20 01:42:52 x1 org.cinnamon.ScreenSaver[20202]: Error in sys.excepthook:
Aug 20 01:42:52 x1 org.cinnamon.ScreenSaver[20202]: Original exception was:
Aug 20 01:44:38 x1 cinnamon-session[4122]: WARNING: t+731.43769s: Detected that screensaver has appeared on the bus
Aug 20 01:45:47 x1 dbus-daemon[628]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.365' (uid=1000 pid=25247 comm="/opt/sublime_text/sublime_text --detached ")
Aug 20 01:45:47 x1 systemd[1]: Starting Hostname Service...
Aug 20 01:45:48 x1 dbus-daemon[628]: [system] Successfully activated service 'org.freedesktop.hostname1'
Aug 20 01:45:48 x1 systemd[1]: Started Hostname Service.
Aug 20 01:46:18 x1 systemd[1]: systemd-hostnamed.service: Deactivated successfully.
```

Kernel 6.2.16 . . generic.

**Comment by LinuxOnTheDesktop** [comment]
I repeat: 'This is a security problem as well as behaviour that throws the user.'

**Comment by przadka** [comment]
I'd like to echo the sentiments of the original post. I'm also experiencing this issue and can confirm its occurrence on my system.

- **System Details**:
- **Distribution**: Mint 21.2
- **Kernel Version**: 5.15.0-86-generic
- **Display Manager**: LightDM
- **Graphics Card**: TigerLake-LP GT2 [Iris Xe Graphics]
- **Driver**: Mesa Intel(R) Xe Graphics (TGL GT2)

The brief exposure of the desktop contents before the lock screen appears is indeed a security concern. In my case, it happens when my laptop is connected to an external monitor. The duration of this exposure is brief, but it's sufficient for someone to potentially capture sensitive information using a camera.

**Comment by LinuxOnTheDesktop** [comment]
[Apparently](https://www.raffriff.com/blog/2021/10/coaxing-linux-mint-to-play-nicely-with-xscreensaver/) one can get 'xscreensaver' to work on Linux Mint. However, one has to either compile from source or use a rather old repository version.

**Comment by LinuxOnTheDesktop** [comment]
I wrote instructions for getting xscreensaver working on Mint Cinnamon. Those instructions are [here](https://pastebin.com/vhXSpJzU) (PasteBin).

**Comment by MatzFan** [comment]
Same issue here on LMDE 6 (faye) installed on an old MacBook Air.

The problem actually seems more acute after installing the latest version (v6.2.1).

**Comment by fritzw** [comment]
For xscreensaver this can be fixed by adding a file to `/usr/lib/systemd/system-sleep` that runs `xscreensaver-command --suspend`. This causes the screen to be locked *before* the CPU goes to sleep (compare [xscreensaver FAQ](https://www.jwz.org/xscreensaver/faq.html#cpu-halt) which implies that this should happen automatically). Maybe a similar fix can be applied to `cinnamon-screensaver`?

However, this would still not fix the issue that the desktop is shown when the monitor configuration changes while locked, e.g. by attaching or unplugging a monitor, rotating a laptop with an orientation sensor (see #460, #436, #414, #406). These problems did not appear with xscreensaver in my testing, but appeared reproducibly with cinnamon-screensaver, to the degree that it cannot be considered a secure way to lock the screen against any but the most hapless attackers.

**Comment by LinuxOnTheDesktop** [comment]
@fritzw 
In addition to some relatively minor problems with xscreensaver, about which I emailed you, I find, now that, on my ThinkPad X230, xscreensaver both blocks my Cinnamon power settings (settings to do with the monitor and going into suspend) and fails to implement its own power settings. Those latter power settings are within xscreensaver-setting's 'advanced' tab and they concern - though one might not guess this from their names - only the monitor. But I cannot manage to make them make the screen blank or put the display into any sort of power-saving state.

So at present the choice for Mint users seems to be: use the Cinnamon screensaver, which shows the desktop briefly before locking and is insecure in other ways; use xscreensaver and give up upon power management. But: @mtwebster : can Cinnamon implement the systemd thingy such that Cinnamon's screensaver, like xscreensaver, does not show the desktop before locking? That is: do we not here have a _solution_ to the bug that this issue (#440) is centrally about?

**Comment by mtwebster** [comment]
The screensaver always locks prior to going to sleep. You can usually see this if you manually suspend the machine. I maintain my explanation for the desktop being briefly visible in some situations. I suspect xscreensaver is just better at this because it's a much lighter program than cinnamon-screensaver (written natively for X11, not using any toolkit like Gtk).

I'm hoping to get the screensaver implemented as part of Cinnamon in one of the next releases, as quite a bit of code we use in cinnamon-screensaver relies on x11-only features. This will be a non-issue once that happens (including x11 sessions, if we choose to use it for both types).

**Comment by LinuxOnTheDesktop** [comment]
@mtwebster : 'in one of the next releases [. . t]his will be a non-issue'. That's great. I add the following though, for what it is worth.

When I tried xscreensaver just now, on a slow computer, xscreensaver did not show the desktop _at all_ when presenting the lock dialogue, whereas, when I had tried xscreensaver _previously_, for a fraction of a second, it _did_ display the desktop.

**Comment by fritzw** [comment]
Same for me with xscreensaver. No amount of sleeping/waking or adding/unplugging/rotating of monitors shows any part of the desktop. With cinnamon-screensaver I can even type in a terminal during the short time when the desktop is visible, e.g. to kill the screensaver process.Glad to hear that this will go away in the future. How do you plan to address the issue for X11 sessions?Am 11.10.2024 um 23:03 schrieb LinuxOnTheDesktop ***@***.***>:﻿
@mtwebster : 'in one of the next releases [. . t]his will be a non-issue'. That's great. I add the following though, for what it is worth.
When I tried xscreensaver just now, on a slow computer, xscreensaver did not show the desktop at all when presenting the lock dialogue, whereas, when I had tried xscreensaver previously, for a fraction of a second, it did display the desktop.

**Comment by LinuxOnTheDesktop** [comment]
@fritzw : part of my comment was confused. Please see how, subsequently, I have edited it.

**Comment by Zapperz0398** [comment]
I have been having the same problem. The lock icon on Linux Mint Cinnamon does not work properly. Initially, I didn't have time to find out why, so I left it and decided to just  use `systemctl` commands in the terminal to lock the screen and then suspend the device.

However, upon waking the system, the desktop is briefly shown unlocked for a second (possibly longer) before the lock screen appears. I assumed it was because the lock command didn't have enough time to process, as the script I run immediately suspends the system after the lock command is invoked

I am using a Wayland session, though.

**Comment by fritzw** [comment]
> You can usually see this if you manually suspend the machine. I maintain my explanation for the desktop being briefly visible in some situations. I suspect xscreensaver is just better at this because it's a much lighter program than cinnamon-screensaver (written natively for X11, not using any toolkit like Gtk).

@mtwebster However, the desktop being visible is not the only thing that xscreensaver does differently. With cinnamon-screensaver, I can actually *type* into a terminal in the supposedly-locked session during the brief moment while the screen is shown. With a macro keyboard, it should not be hard to type `<Alt+F2>killall cinnamon-screensaver<ENTER>` in a split-second to unlock the screen.

With cinnamon-screensaver this flashing of the desktop can be easily triggered, on demand. But with xscreensaver no amount of waking/sleeping or plugging or unplugging monitors (while hammering on the keyboard like a madman) allowed any input to pass through to the locked desktop. Even if the desktop was accessible for only a few milliseconds, at least one of the hundreds of keystrokes should have passed through, so I suspect that xscreensaver does something fundamentally different like grabbing the keyboard globally, or some such thing (I'm not an X11 expert myself).

**Comment by nNoidea** [comment]
problem also exist in Mint 22

**Comment by Handshake2205** [comment]
Worse than just showing the desktop, I was too quick to enter my password and it typed it into a WhatsApp (ZapZap) group chat and sent it before the screen lock dialog kicked in!!

ZapZap was the active window prior to locking the screen. Luckily, I noticed what had happened and I immediately deleted the message from the group chat, but this is a MAJOR security bug.

**Comment by reflector8939** [comment]
Same problem here:  when i turn on my PC while in sleeping mode it briefly shows the desktop before showing the logging page

is there a solution?


<img width="810" height="594" alt="Image" src="https://github.com/user-attachments/assets/7a44d97b-131c-4343-8794-9061c0fa96fe" />

**Comment by LinuxOnTheDesktop** [comment]
I believe that - as I said, pretty much, above - that this problem can only be, and hopefully will be, solved with the transition to Wayland. The good news is that that transition is due fairly soon.

**Comment by mtwebster** [comment]
cinnamon-settings-daemon 6.6.4 was released today for Mint 22.3 and LMDE7, which should improve this behavior quite a bit (though it's still theoretically possible for it to occur in x11 sessions).

ref:
https://github.com/linuxmint/cinnamon-settings-daemon/commit/e4090ed6fbbe69fc76d91c69effaae20034fd7e9
https://blog.linuxmint.com/?p=5010 (part of discussion of the new screensaver was about an issue we discovered and fixed in cinnamon-settings-daemon).

**Comment by aaronwi** [comment]
was this fixed upstream in debian as well? 3 years later..still an issue

**Comment by mtwebster** [comment]
It would be up to the Debian Cinnamon maintainer.  We only updated the latest version (6.6.x) but Trixie is on 6.4.x... the commit could definitely be backported though.

@Fantu

**Comment by Fantu** [comment]
I've seen the new version, and I'll upload it to unstable in the next few days. I'm not sure if I'll have time to do an SRU (testing and everything else is needed), so maybe I'll ask the team's new DD if he want.

**Comment by aaronwi** [comment]
> It would be up to the Debian Cinnamon maintainer. We only updated the latest version (6.6.x) but Trixie is on 6.4.x... the commit could definitely be backported though.
> 
> [@Fantu](https://github.com/Fantu)

I think this issue is farther up, it happens in vanilla debian

**Comment by Mintulix** [comment]
cinnamon-settings-daemon 6.6.4+zena now
X11, LM 22.3, Cinnamon 6.6.7, no updates missing

Sorry to say, no difference here - still one second desktop before lock screen after suspend

**Comment by Fantu** [comment]
So the issue is still present?
Can be useful to know in what cases is still reproducible, is in case of multiple monitor? Or after return from suspend also with single monitor?

**Comment by LinuxOnTheDesktop** [comment]
For my part (I created the thread, but multiple others have chimed in saying 'me too) I have not seen the problem for a while. However: it was always intermittent; nearly always I use only a single monitor.

**Comment by GernBlanston12** [comment]
I want to chime in and note I found this thread upon search for the issue I was having. Same thing as recently as 1 day ago, where the desktop is visible for some fraction of a second long enough to be photographed, while the machine is coming out of suspension/moving to lock screen and before password input. I have multiple monitors, Mint 22.3, Cinnamon 6.6.7, X11, but this has happened where one monitor is off and the other turned on going to lock/password screen from suspend. A malicious actor could thus get a photo or screenshot of my desktop while the machine was left suspended, even without engaging the lock screen/password in any way.
