### ISSUE TITLE
Black band with 2.2.4-1 on ArchLinux.

### ISSUE THREAD

**Issue by clfarron4** [linuxmint/cinnamon-screensaver#56]
On ArchLinux, I now have a black band across the screensaver with 2.2.4-1:

https://lh3.googleusercontent.com/-CfyzGctphBw/U53Sa5c5tuI/AAAAAAAABvw/4VQ6Hbje_f0/w793-h446-no/140615Screensaver224.png

Downgrading to 2.2.3-1 resolves problem:

https://lh5.googleusercontent.com/-1QRj-QAcWt4/U53Scv4AKhI/AAAAAAAABv4/yOkk-66PVwo/w793-h446-no/140615Screensaver223.png

**Comment by clefebvre** [comment]
Fixed in 2.4.1.

**Comment by Vusys** [comment]
Still an issue in 2.4.1. Using Manjaro Linux with cinnamon-screensaver 2.4.1 installed manually from the Arch repos.

**Comment by ManuelSchneid3r** [comment]
Still an issue in cinnamon 2.4.6
![Black bar image](http://i.imgur.com/5eS1eAx.jpg)
Maybe this [this thread](https://bbs.archlinux.org/viewtopic.php?id=184664)helps. It contains a "patch" and is marked as solved. I did not test this.

**Comment by DrPandemic** [comment]
Since my last cinnamon-screensaver update, I didn't get one black bar. So make sure your cinnamon-screensaver is up to date and not just cinnamon! The only difference I see in the arch post and in the current code/fix by clefebvre is the 
```
GdkColor transparentColor = { 0, 0, 0, 0 };
```
into
```
GdkColor transparentColor = { 0, 0, 0, 1 };
```
I would try to make the change, but since I don't anymore have the problem it would be useless. So @
ManuelSchneid3r or @Vusys you could try the fix for us. I remember that I already tried to build cinnamon-screensaver on Arch and it was not too much complicated.

**Comment by mtwebster** [comment]
Fixed for good by this: https://github.com/linuxmint/cinnamon-screensaver/commit/bfb41fb734c6c2525b9cee4b4c9f13ef7fa69305

in 2.4.2 now
